### ISSUE TITLE
Add support for Matrix API calls with more than 25 coordinates

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-java#1124]
In certain situations and with Mapbox approval, Matrix API calls can be made with 50 coordinates instead of the normal 25 maximum. This ticket tracks the idea of adjusting the Java SDK so that the SDK supports the 50 coordinate calls.

https://github.com/mapbox/mapbox-java/blob/master/services-matrix/src/main/java/com/mapbox/api/matrix/v1/MapboxMatrix.java#L306-L312

Related:

- https://docs.mapbox.com/android/java/overview/directions-matrix/
- https://docs.mapbox.com/android/java/examples/get-a-travel-time-matrix/

cc @brandihaskins

**Comment by langsmith** [comment]
@danpat 's thoughts on this

"the SDKs shouldn't have any limits in them - limits are customizable per-account and controlled server/API side"

This is probably the right way to go. Remove the coordinate size check at https://github.com/mapbox/mapbox-java/blob/master/services-matrix/src/main/java/com/mapbox/api/matrix/v1/MapboxMatrix.java#L306-L312 and let the server/API side handle limits.

**Comment by zugaldia** [comment]
I'd prefer setting a default limit that is configurable by the developer to avoid running into memory issues (e.g. https://github.com/mapbox/mapbox-java/issues/893).

**Comment by danpat** [comment]
@zugaldia We'd want to document that pretty clearly - it seems like it'll be confusing to have limits configurable both in the SDK, *and* by contacting sales reps.

Besides, if someone has a high-configured limit server-side, and allows high-coordinate-counts in the SDK, it seems like the issues in #893 would occur anyway, as the root cause of that bug was never really resolved that I can see.

**Comment by zugaldia** [comment]
@danpat that's fair. I'm only worried that the SDK would not provide any safeguards for limits that are documented and that might surprise the dev. On the other hand, keeping SDK docs in sync with API docs have been a challenge in the past because we follow a different release pace.

@langsmith Let's get some customer feedback on your approach here https://github.com/mapbox/mapbox-java/compare/matrix-max-50-snapshot-fix.

**Comment by langsmith** [comment]
> your approach here https://github.com/mapbox/mapbox-java/compare/matrix-max-50-snapshot-fix.

I deleted the `matrix-max-50-snapshot-fix` branch. The only work on that branch was my changing https://github.com/mapbox/mapbox-java/blob/master/services-matrix/src/main/java/com/mapbox/api/matrix/v1/MapboxMatrix.java#L310 from 25 to 50.

**Comment by langsmith** [comment]
cc @chloe so that she can follow along
