### ISSUE TITLE
Release v5.2.2 + backport to v4.9.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#1154]
With https://github.com/mapbox/mapbox-java/pull/1153 merged, we will need to publish a new release for mapbox-geojson. Additionally this PR needs a backport to 4.9.x to support non-androidx builds of the maps SDK. 

cc @zugaldia

**Comment by zugaldia** [comment]
cc: @langsmith @abhishek1508

**Comment by langsmith** [comment]
@abhishek1508 and I paired together and did the 5.3.0 release together https://github.com/mapbox/mapbox-java/issues/1155 & https://github.com/mapbox/mapbox-java/releases/tag/v5.3.0

`5.3.0` because it included a new feature/method https://github.com/mapbox/mapbox-java/releases/tag/v5.3.0

Anyways, I haven't forgotten about the required backport. This is my first time backporting, so I'm looking into the easiest way to backport and apply https://github.com/mapbox/mapbox-java/pull/1153 work.

**Comment by langsmith** [comment]
https://github.com/mapbox/mapbox-java/releases/tag/v4.9.1 went out two days ago. We're good to close this ticket. Please re-open and comment if there are any issues and/or follow up work is needed.
