### ISSUE TITLE
Mapbox-sdk-services 5.4.0 is missing libraries

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-java#1191]
https://dl.bintray.com/mapbox/mapbox/com/mapbox/mapboxsdk/mapbox-sdk-services/5.4.0/

Found a minor issue when building a validator for the directions-api https://github.com/mapbox/mapbox-java/pull/1189

https://bintray.com/mapbox/mapbox/mapbox-sdk-services/5.4.0
Notice, 5.4.0 is missing releases
![Screen Shot 2020-09-23 at 1 08 32 PM](https://user-images.githubusercontent.com/3021882/94064030-e4e30f00-fd9d-11ea-907d-2bc5febfcde5.png)

Expected, shown with 5.4.1
https://bintray.com/mapbox/mapbox/mapbox-sdk-services/5.4.1
![Screen Shot 2020-09-23 at 1 06 12 PM](https://user-images.githubusercontent.com/3021882/94063858-99306580-fd9d-11ea-931c-8bd4d492a782.png)

**Comment by langsmith** [comment]
Yes, when I was rolling with the `5.4.0` release, I noticed that some modules were missing files. https://app.circleci.com/pipelines/github/mapbox/mapbox-java/71/workflows/8cd52c64-b70c-415b-846a-dea5377352ee/jobs/4217

That's why I ended up making `5.4.1` to re-attempt getting all of the files to Bintray https://github.com/mapbox/mapbox-java/releases/tag/v5.4.1

Is this blocking you for some reason?

**Comment by kmadsen** [comment]
Not blocking anything, just noting. Closing as won't fix
