### ISSUE TITLE
Bump okhttp to 4.x

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#1248]
Maps, Nav and Search have switched to using OkHttp 4.x, we need to bump the version from this repo as well.

cc @kiryldz @LukasPaczos @DzmitryFomchyn

**Comment by kiryldz** [comment]
For context because of using `com.mapbox.mapboxsdk:mapbox-sdk-services:5.4.1` with our latest Maps `com.mapbox.maps:android:10.0.0-beta.16` here https://github.com/mapbox/studio-preview-android/pull/436 there was a bit confusing runtime error related to automatically resolving `com.squareup.okhttp3:logging-interceptor:3.12.7` which is not compatible with our upgraded okhttp 4+.
