### ISSUE TITLE
Remove outdated API wrappers projects

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#143]
All the functionality once provided by https://github.com/mapbox/mapbox-directions-android and https://github.com/mapbox/mapbox-geocoder-android is now provided and augmented by this project. To avoid confusing developers and because we don't intend to maintain those two projects any more, we should shut them down.

In order to do that we need to:
- [x] Make sure that any of the issues / PRs in https://github.com/mapbox/mapbox-directions-android are no longer relevant, or migrate them to this repo.
- [x] Make sure that any of the issues / PRs in https://github.com/mapbox/mapbox-geocoder-android are no longer relevant, or migrate them to this repo.
- [x] Decide with @tmcw whether to delete the repos, make them private, or move them to another organization

/cc: @cammace

**Comment by cammace** [comment]
Went through both repos and only found [progaurd](https://github.com/mapbox/mapbox-directions-android/issues/12) issues that might be relevant since I personally haven't test this out. I think sirius is using progaurd though and not having any issues. If this is the case, all issues/PRs are resolved in MAS.

**Comment by zugaldia** [comment]
@cammace Much appreciated.

**Comment by cammace** [comment]
Both repos have been made private, closing issue.
