### ISSUE TITLE
Add pin to static image

### ISSUE THREAD

**Issue by drac94** [mapbox/mapbox-java#213]
It would be nice if an option to get an image with a pin (customizable or default) at the center point can be added, or maybe add it including an extra layer in the top of the image. I didn't found a way to do that.

**Comment by cammace** [comment]
The static image API doesn't give an option for adding a marker to the map. The solution for this would be to place your `ImageView` which you'll be adding the map to inside a `FrameLayout` and adding a marker image on top of the map. I will share your feedback with the team, closing ticket since this repo only wraps the API.
