### ISSUE TITLE
Add optional language parameter to geocoder

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#281]
iOS allows the option to [pass in a language](https://github.com/mapbox/MapboxGeocoder.swift/blob/master/MapboxGeocoder/MBGeocodeOptions.swift#L101) parameter. My understanding of it is that it isn't part of the geocoder API but rather something done inside the library itself. @1ec5 can you elaborate a bit more on the behavior on this and whether we should implement it in MAS?

cc: @zugaldia

**Comment by 1ec5** [comment]
Here's [the documentation for this option](https://github.com/mapbox/MapboxGeocoder.swift/blob/af6119f6a253b2ab60c69e4970f64dfbc3a390a5/MapboxGeocoder/MBGeocodeOptions.swift#L56-L65).

MapboxGeocoder.swift lets the developer specify an NSLocale (a standard Apple-platform object representing a locale); it extracts the language code from that NSLocale and passes it into the API. Currently, the default leaves the locale unspecified, because the option is experimental, but in internal applications we've been passing in the system locale.

**Comment by 1ec5** [comment]
The Geocoding team is fine with us exposing this option, as long as we mark it as experimental and clarify its purpose (just the display language).
