### ISSUE TITLE
MapNavigation.getRoute should take an origin and destination as parameters

### ISSUE THREAD

**Issue by boconnell** [mapbox/mapbox-java#376]
Otherwise, you force the consumer of the API to realize they must call setOrigin and setDestination manually. Resetting the origin and/or destination in the middle of a navigation session would also cause inconsistencies between the origin & destination and the route until the consumer calls getRoute again. Making them parameters seems more clear?

**Comment by cammace** [comment]
I agree with this, `getRoute()` should take in the origin and destination. Removing setOrigin and setDestination will indeed prevent people from setting these during a navigation session and instead use a proposed API called `MapboxNavigation.updateRoute()` which can request a new route and handle rerouting properly (since rerouting is different then getting the initial route). 

cc: @zugaldia

**Comment by cammace** [comment]
This was fixed in the nav sdk. closing
