### ISSUE TITLE
Update GeocoderAutoCompleteView to use RxJava's debounce

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#4]
Reference implementation: https://github.com/kaushikgopal/RxJava-Android-Samples/blob/master/app/src/main/java/com/morihacky/android/rxjava/fragments/DebounceSearchEmitterFragment.java

Based on https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxAutoCompleteTextView.java.

**Comment by munyamikehove** [comment]
Came here because i can't seem to access GeocoderAutoCompleteView service when creating autocomplete widget . 

Added 
1. <service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" /> to my Android manifest 
2. compile('com.mapbox.mapboxsdk:mapbox-android-sdk:4.0.1@aar') {
        transitive = true
    }
and 
compile ('com.mapbox.mapboxsdk:mapbox-android-geocoder:1.0.0@aar'){
        transitive=true
    }
to my build.gradle app module 
3. mavenCentral() to my build.gradle project 

what could be missing ?

**Comment by zugaldia** [comment]
@munyamikehove Thanks for trying MAS. This information however isn't relevant to this ticket, could you please send a note to `help@mapbox.com` instead? Thanks.

/cc: @cammace

**Comment by zugaldia** [comment]
Related: https://github.com/mapbox/mapbox-java/issues/131

**Comment by zugaldia** [comment]
It's unclear that `debounce` would bring benefits that could make up for the size of the Rx dependency. Let's close for now unless there's a clear usecase / need.
