### ISSUE TITLE
automatically activate locationengine if request updates made.

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#403]
These terms can often times be mixed up and cause confusion, it also looks to me like it causes boilerplate code since you can `connect` the location provider also in `requestLocationUpdates`. We can still expose these methods for `activate()` and `deactivate()` but we can also automatically try to connect when the user calls `requestLocationUpdates()` since it's required to activate first anyways. 

cc: @zugaldia

**Comment by zugaldia** [comment]
@cammace I'm wondering about the case where you want to `connect` but want to handle `requestLocationUpdates` separately. Instead of merging both methods, would it make sense to automatically `connect` when you call `requestLocationUpdates` if you haven't yet? Or provide a warning to the developer?

Also, do you want this to happen at the `LocationEngine` interface level, or for one specific implementation?

**Comment by cammace** [comment]
I like this idea also. I also think you can simply activate the location engine and get the last known location without having to requestLocationUpdates so removing it wouldn't be ideal. I think it's a good idea to still automatically connect to the location provider inside the requestLocationUpdates (deactivate when removingLocationUpdates).

**Comment by zugaldia** [comment]
@cammace I like that.

Also, we could always query `getLastLocation()` with the first invocation of `requestLocationUpdates()` to try to get something reported quicker.

**Comment by cammace** [comment]
@Guardiola31337 @electrostat Can this be moved to the new telem repo or closed if you guys feel this functionality is no longer needed.
