### ISSUE TITLE
Remove ServiceException and TurfException

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#555]
There's little reason to keep these exceptions around since making them into Runtime Exceptions and might make more sense to directly use the `RuntimeException` class.

cc: @zugaldia

**Comment by zugaldia** [comment]
I think that calling them `RuntimeException` is too generic and doesn't provide enough context to the developer. Alternatively, are there any [subclasses](https://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html) that we could use instead? E.g. `IndexOutOfBoundsException` if the issue is with a bad Turf/Service array index.

**Comment by cammace** [comment]
makes sense, I have actually added a GeoJSON exception and as you mention, we can also push on adding more Runtime subclasses wherever possible. Closing.
