### ISSUE TITLE
Fix turnstile events

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-java#573]
The iOS & Unity SDKs added a new `sdkIdentifier` event to `appUserTurnstile` to be able to differentiate turnstile events between the maps sdks and other sdks. 

We need to add `sdkIdentifier` as an attribute and let the SDKs set this. 

For example, the navigation SDKs would set `sdkIdentifier` to either `mapbox-navigation-ui-android` or `mapbox-navigation-android`.

cc @Guardiola31337 @zugaldia @mick @boundsj

**Comment by ericrwolfe** [comment]
iOS implementation: https://github.com/mapbox/mapbox-events-ios/blob/f118bea60d7ac08414585a1b4ba6051ef5a0cf83/MapboxMobileEvents/MMEEventsManager.m#L226

**Comment by zugaldia** [comment]
We already let the implementing SDK manually set a custom user agent string, which is what the linked iOS method seems to do. This can be done at [initialization time](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L116) or calling a [dedicated method](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L205). Would that meet the requirement?

**Comment by ericrwolfe** [comment]
@zugaldia We could use the information from the custom user agent string, but that means we'd need to parse the string to separate the events by SDK. Our telemetry pipeline is configured to use the `sdkIdentifier` field to distinguish turnstile events across our Maps, Navigation, and Unity SDKs.

iOS made changes to make telemetry more universal here https://github.com/mapbox/mapbox-events-ios/commit/6e09b045fa37583e1884fef249a5b325fc1e82fd

In addition, setting a custom user agent [at initialization time](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L116) doesn't seem to work correctly, though [calling the dedicated `newUserAgent()`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L205) method seems to workaround the issue.

**Comment by zugaldia** [comment]
cc: @electrostat for visibility on the Android side.

**Comment by Guardiola31337** [comment]
@ericrwolfe 
> setting a custom user agent [at initialization time](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L116) doesn't seem to work correctly, though [calling the dedicated `newUserAgent()`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L205) method seems to workaround the issue.

The "_problem_" that we have with the current implementation is that you can only initialize telemetry once 👀 https://github.com/mapbox/mapbox-java/blob/a58b53b016039e8c85987073893c3b778c832a63/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L129-L131 and if you include the Map SDK in your app, telemetry is initialized by the Map SDK behind the scenes when a map is loaded which means that if we "_set_" a custom user agent calling [`initialize`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L116) after telemetry being initialized that call doesn't have any effect (because of the guard clause).

In order to workaround that, we introduced the new user agent API `newUserAgent(String userAgent)` in https://github.com/mapbox/mapbox-java/pull/568 which should do the trick.
We should initialize telemetry as always and then we’d need to call `MapboxTelemetry.getInstance().newUserAgent("<userAgent>");` when needed. Only thing that we need to take into account is that we need to pass a valid user agent 👀 https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L80-L88

**Comment by cammace** [comment]
This has been resolved correct? Can we close or move to the appropriate repo?
