### ISSUE TITLE
Define constants for Geocoding API categories

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-java#582]
The Geocoding API has introduced [experimental support for category search](https://www.mapbox.com/api-documentation/#poi-categories). The Geocoding API doesn’t currently support natural language queries; instead, you specify one of a number of predefined keywords as the query and `poi` as the `type` (and typically a `proximity` parameter). An application can present the user with a series of buttons for common categories to search for.

Category search currently works without any modifications to this library. However, we can improve the feature’s discoverability by providing constants for the most common categories. The set of categories is open-ended and subject to change, so the constants should all be strings. We should mark this constants as `experimental` until the “Preview” tag is removed from the API documentation.

/cc @cammace

**Comment by 1ec5** [comment]
mapbox/MapboxGeocoder.swift#119 is the equivalent issue for Apple platforms.

**Comment by cammace** [comment]
If I'm reading the API correctly, the amount of categories is currently at 428 which is a ton of Constants. The categories listed in the API docs are just some of the popular ones. I'd rather include all of them or none and since the categories is essentially a search query (from the geocoder wrapper standpoint) it wouldn't really make sense to make these into an enum that the query string parameter would take in.
