### ISSUE TITLE
[BUG] nothing when search TYPE_ADDRESS in Geocoder

### ISSUE THREAD

**Issue by darkwizzard** [mapbox/mapbox-java#711]
Hello, there is a bug  when i try use GeocodingCriteria.TYPE_ADDRESS, there is not results. If i use TYPE_POI it get the POIs.

I had not modified the code, it is a bug in the api, can you check this please?

**Comment by cammace** [comment]
I ran a check on the API using this query with the latest code on master and received 5 results (as I'd expect).

```java
MapboxGeocoding geocoding = MapboxGeocoding.builder()
      .geocodingTypes(GeocodingCriteria.TYPE_ADDRESS)
      .accessToken(BuildConfig.MAPBOX_ACCESS_TOKEN)
      .query("1600")
      .build();
```

This is most likely due to which country you are doing the search in. Have a look at our [coverage map](https://www.mapbox.com/geocoding/#coverage). Going ahead and closing since this issue isn't related to this library.

**Comment by darkwizzard** [comment]
@cammace yeah it works with other countries but my country is in coverage map for address search. Where can i comment for this issue? Thanks.
