### ISSUE TITLE
Synchronize with renamed Turf.js functions

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-java#723]
[This document](https://github.com/mapbox/mapbox-java/blob/master/docs/turf-port.md) listing Turf.js function names was last updated in October. Since then, the JavaScript version of Turf has renamed some modules. Here’s a non-exhaustive list off the top of my head:

* [ ] `turf-point-on-line` → `turf-nearest-point-on-line`
* [ ] `turf-line-distance` → `turf-length`

This document should be updated. Beyond that, should the corresponding functions in this Java port be renamed as well?

/cc @cammace @zugaldia

**Comment by zugaldia** [comment]
cc: @osana

**Comment by cammace** [comment]
We can either go ahead and rename these in the turf module since next release will be SEMVER or we can deprecate the current names and add two new methods with the correct naming. The later might be nicer to navigation and others who are using these methods and won't suddenly have to change the name when updating.

**Comment by zugaldia** [comment]
I'd rather take advantage of the upcoming SEMVER change to minimize naming inconsistencies. The API change should be a straightforward one.
