### ISSUE TITLE
Remove Android references from project documentation

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#771]
I see several mentions to `android` in the `README.md` as well as the main link in the repo description. Since v3.x this repo is 100% Java so we should remove those references to clarify the updated state of the project.

cc: @osana

**Comment by osana** [comment]
@zugaldia @cammace in that vein we should then stop using android annotations from the support library.  ```import android.support.annotation.*```

**Comment by cammace** [comment]
This shouldn't be an issue @osana, In the [annotation project docs](https://developer.android.com/studio/write/annotations.html) directly, they mention:

> If you want to use annotations in a Gradle module that is not using the Android plugin for Gradle (com.android.application or com.android.library) but is using the Gradle Java plugin instead, you must include the SDK repository explicitly because the Android support libraries are not available from the JCenter Java repository...

I remember doing some research on this (because of how useful annotations are) to see if I could somehow use it in a java project and found a few projects doing this, though, I can't specifically point to any right now as I forgot. 

> Adding the support-annotations dependency does not introduce a dependency for any downstream users of your library.

^ This seems to be true if you check [the pom files](https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-sdk-core/3.0.0/mapbox-sdk-core-3.0.0.pom) in the 3.0 release you won't see the annotation dependency. 

For further confidence in safely including the annotations library in this project, the [sample app](https://github.com/mapbox/mapbox-java/blob/master/samples/build.gradle) only depends on the library modules and seems to compile fine. Though if I am missing something let me know.

**Comment by zugaldia** [comment]
> @zugaldia @cammace in that vein we should then stop using android annotations from the support library. import android.support.annotation.*

Good thinking. Could you catalog which annotations are we using and cut a separate ticket so that we could keep this ticket to track the documentation changes? If we're only using nullability annotations there might be better libraries we could use.

**Comment by osana** [comment]
Indeed we use mostly :
android.support.annotation.Nullable
android.support.annotation.NonNull

There are also a couple occurrences of :
android.support.annotation.FloatRange
android.support.annotation.IntRange
import android.support.annotation.StringDef
android.support.annotation.Size

**Comment by osana** [comment]
README was addressed by #779

**Comment by osana** [comment]
main issue of this PR was addressed.  annotations support can be addressed later if needed
