### ISSUE TITLE
Integrate static analysis tool with project.

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#918]
There're static analysis tools for Java/Android that catch common programming mistakes at compile-time. Examples are:
- https://github.com/google/error-prone
- https://fbinfer.com/

I'd like to pick a preferred tool by the team and integrate it with this repo's CI infrastructure. If we're happy with the results, we could bring this set up to other SDK projects.

/cc: @mapbox/maps-android

**Comment by tobrun** [comment]
@zugaldia why would we use `error-prone` or `fbinfer` above `lint` for android based projects?

**Comment by zugaldia** [comment]
That's a fair question. From my brief knowledge of these tools, my understanding is that both are able to detect Java and Android-specific issues (like lint) so I was hoping for additional checks to be added. Maybe as a first step before working on integration is comparing the output of all tools to see if there's any actual value added.

We have anecdotally used Infer in the past: https://github.com/mapbox/mapbox-gl-native/issues/9814, for the core library.

**Comment by cammace** [comment]
I added errorprone already in this library awhile back in https://github.com/mapbox/mapbox-java/commit/719ee3195e4698708dba8e391855922381bd8504. I never really finished configuring it with options though since I ultmately went with the SonarQube tooling which included all of errorprones rules in their analysis. I see yall removed SonarQube recently, just FYI, the dashboard still exist [externally here](https://sonarcloud.io/dashboard?id=mapbox-java-services%3Amaster). I can remove it if no one else has access.

**Comment by langsmith** [comment]
Thanks @cammace . Looks like I have access to remove the project/organization if/when need be.

![Screen Shot 2019-04-02 at 3 37 57 PM](https://user-images.githubusercontent.com/4394910/55440677-52bdca00-555d-11e9-81f8-11d230ee2673.png)
![Screen Shot 2019-04-02 at 3 37 47 PM](https://user-images.githubusercontent.com/4394910/55440678-52bdca00-555d-11e9-9ebb-01a5ed9af85f.png)

**Comment by zugaldia** [comment]
@cammace fancy to see you around here! 

@langsmith where you able to remove our SonarQube instances or do you need @cammace's :hocho: ?

**Comment by langsmith** [comment]
Organization deleted in Sonarcube. RIP.

**Comment by osana** [comment]
Thank you @langsmith
