### ISSUE TITLE
Query congestion near a coordinate

### ISSUE THREAD

**Issue by mingxin-yang** [mapbox/mapbox-java#926]
WHat kind of issue is this?

- [x] **Questions** are better to ask on [Stack Overflow](https://stackoverflow.com/questions/tagged/mapbox+android). We are actively monitoring the questions there and oftentimes, others have already asked a similar question.
- [ ] **Feature request** should start off by describing the problem the feature will resolve. Please open a GitHub ticket beforehand with information about the feature to spark some discussion about the topic and once you have our support.  
- [ ] **Bug Report** can be reported using the provided template below:

#### Steps to Reproduce

1.
2.
3.
4.

**Comment by mingxin-yang** [comment]
Do you have this Features？

**Comment by osana** [comment]
@mingxin-yang Not sure what Features are you looking for?

**Comment by langsmith** [comment]
Hi @mingxin-yang, I'm going to close this ticket because this is a Mapbox implementation question rather than an issue with the Mapbox Java SDK.

If you're still interested in figuring out how to find the congestion level, please contact the Mapbox Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and they'll help you.
