### ISSUE TITLE
Add waypoint indices option for Directions API

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#956]
The Directions API will soon expose a waypoints parameter similar to the Map Matching API’s: Project-OSRM/osrm-backend#5345. 

We should add / account for this parameter - iOS equivalent in https://github.com/mapbox/MapboxDirections.swift/issues/334

**Comment by 1ec5** [comment]
This SDK exposes the `waypoints` parameter as a simple array of integers, so the same code could probably be copied to RouteOptions.

https://github.com/mapbox/mapbox-java/blob/22a324ffc37389cebee20aa49e83c08c13221a98/services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java#L337

mapbox/MapboxDirections.swift#334 discusses some refactoring we’d like to do on the Swift side to make the option more object-oriented, but the approach in Java might differ since this SDK follows the Builder pattern.

**Comment by osana** [comment]
@1ec5 good point about RouteOptions. Thank you for bringing it up.

I think you are absolutely right those should be added to the RouteOptions.
In fact they should be added to RouteOptions in MapMatching as well.
