### ISSUE TITLE
Move to Bintray for Mapbox Java SDK releases

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-java#995]
Right now, Mapbox Java Sdk uses Sonatype to pass release files on to MavenCentral.
Recently, Maps SDK Android switched to using [Bintray](https://bintray.com).  
We want to align the release process used in those two projects and to use Bintray for Mapbox Java Sdk releases.

Here is the [PR](https://github.com/mapbox/mapbox-gl-native/pull/13999) used to move to Bintray in Maps SDK Android for reference.

**Comment by langsmith** [comment]
Love the idea of getting more projects on to the sample platform. Bintray integrations and its UI are all great.

**Comment by langsmith** [comment]
I added the needed environment variables to the Java SDK project in CircleCI

**Comment by langsmith** [comment]
I've added an initial setup for this on https://github.com/mapbox/mapbox-java/pull/new/ls-moving-release-process-to-bintray

I've made good progress but I'm running into a crash that probably has to do with where I'm (not) adding Gradle `apply from` statements

![Screen Shot 2019-04-22 at 5 31 08 PM](https://user-images.githubusercontent.com/4394910/56542855-8e2c3280-6524-11e9-98b0-ac4327641f0f.png)


https://discuss.gradle.org/t/problem-with-publishing-with-maven-publish-in-a-multi-module-project-ii/22318

https://discuss.gradle.org/t/problem-with-publishing-with-maven-publish-in-a-multi-module-project/1695/3

https://github.com/novoda/bintray-release/issues/24

**Comment by langsmith** [comment]
Ok @osana & @LukasPaczos , https://github.com/mapbox/mapbox-java/pull/new/ls-moving-release-process-to-bintray has my most up-to-date work. 

One thing I thought about looking into is using a different Bintray publishing plugin, such as https://github.com/novoda/bintray-release . Perhaps a different plugin can handle the multiple components that are in the `services` package.

**Comment by LukasPaczos** [comment]
> Perhaps a different plugin can handle the multiple components that are in the services package.

Now that I think about it, what's the issue with pushing each artifact separately to Bintray? We'll probably still need to click the `sync` button on each artifact separately. Your current setup seems to be adapted well to do that, are you running into any issues?

The only piece that I think might be missing is that we need to recognize in the `Makefile#publish` or CI script whether a version is a `SNAPSHOT` or a stable/alpha version which was previously handled by the maven-release plugin.

**Comment by langsmith** [comment]
> pushing each artifact separately to Bintray

Not sure what you mean. Can you elaborate? You're suggesting each API wrapper artifact (optimization, mapmatching, etc.) should be sent separately to Bintray first?  Or something different?

> The only piece that I think might be missing is that we need to recognize in the Makefile#publish or CI script whether a version is a SNAPSHOT or a stable/alpha version which was previously handled by the maven-release plugin.

Ok, will look into this. Working off of https://github.com/mapbox/mapbox-gl-native/pull/14067, I pushed/re-based changes to start the work of setting the SNAPSHOT repository to https://oss.jfrog.org/artifactory/oss-snapshot-local/. If this shouldn't be done, let me know.

**Comment by LukasPaczos** [comment]
> You're suggesting each API wrapper artifact (optimization, mapmatching, etc.) should be sent separately to Bintray first? Or something different?

No, phrased that poorly. We have 4 releasable modules, `core`, `services`, `geojson`, `turf`. All those non-releasable modules are declared as code source sets for `services`, not as dependencies, so there should be no issues here.

> Perhaps a different plugin can handle the multiple components that are in the services package.

Just a hunch, but this error might be thrown because you are first applying the bintray plugin that defines a publication to, for example, `core` and then using that as a dependency in `services` which applies the bintray plugin again.

Another issue might arise when we get to dependencies on other projects, for example:
https://github.com/mapbox/mapbox-java/blob/7120a5060b09b1972ca67e00b46b10b807589619/services-turf/build.gradle#L8
or
https://github.com/mapbox/mapbox-java/blob/7120a5060b09b1972ca67e00b46b10b807589619/services/build.gradle#L13-L14
those dependencies might not be picked up in `POM` (or are represented poorly, like `unknown` or wrong artifact names).

References in the `POM` to those modules need to be based on their Maven releases. Gradle is unable to determine if, or which version of the artifact it should use because we are consuming a local module.

So, whenever we release a module, during the `POM` generation we need to iterate through all of its dependencies and for each local dependency we need to overwrite that module value with a correct artifact name and version of the most recent Maven release of that dependency. We can either store those locally, next to the current SNAPSHOT version name or query them from the Maven repository.

**Comment by LukasPaczos** [comment]
When it comes to snapshots, we need to first create a new project in https://bintray.com/mapbox/mapbox/ (this is needed for regular releases as well) and request JCenter access to be able to push to the snapshot repository.

**Comment by osana** [comment]
A bit of a side note but maybe it would be helpful.

It is easy to merge service-core into services. 
Dependency on service-core in services-geojson is minimal.

But if we want to be able to release each of the sub-services individually than this is not actionable.

**Comment by langsmith** [comment]
Still lots to fix, but I made good progress today 👍  `make build-release` and then `make publish` was able to push files to Bintray


![Screen Shot 2019-05-16 at 3 26 12 PM](https://user-images.githubusercontent.com/4394910/57891144-30bb9680-77ef-11e9-9dfd-dfaf79eb2e38.png)

See page 2 of https://bintray.com/mapbox/mapbox

https://bintray.com/mapbox/mapbox/mapbox-sdk-services/4.9.0-SNAPSHOT#files/com/mapbox/mapboxsdk/services/4.9.0-SNAPSHOT


![Screen Shot 2019-05-16 at 3 28 38 PM](https://user-images.githubusercontent.com/4394910/57891184-5052bf00-77ef-11e9-8338-3c1a26cd3759.png)
![Screen Shot 2019-05-16 at 3 28 35 PM](https://user-images.githubusercontent.com/4394910/57891185-5052bf00-77ef-11e9-871c-9ee0a8bf690d.png)

**Comment by langsmith** [comment]
Also, seems that the Java wrappers (optimization, mapmatching, etc.) were successfully included in the `services` module. 👇 is from unzipping the `services` module's `.jar` file found at https://bintray.com/mapbox/mapbox/mapbox-sdk-services#files/com/mapbox/mapboxsdk/services/4.9.0-SNAPSHOT

![Screen Shot 2019-05-16 at 3 47 00 PM](https://user-images.githubusercontent.com/4394910/57891922-00c1c280-77f2-11e9-8eff-52ade0d44be5.png)

**Comment by langsmith** [comment]
@LukasPaczos , a couple of things based on my latest update above:


Regarding my past :boom: of `cannot include multiple components`: 
This seems to have been solved by adding the two lines within `subprojects` rather than pasting `apply plugin: "${rootDir}/gradle/gradle-bintray.gradle"` in the four release modules' `build.gradle` files.
 
- https://github.com/mapbox/mapbox-java/compare/ls-moving-release-process-to-bintray?expand=1#diff-c197962302397baf3a4cc36463dce5eaR106

- https://github.com/mapbox/mapbox-java/compare/ls-moving-release-process-to-bintray?expand=1#diff-c197962302397baf3a4cc36463dce5eaR107

>Now that I think about it, what's the issue with pushing each artifact separately to Bintray? We'll probably still need to click the sync button on each artifact separately. Your current setup seems to be adapted well to do that, are you running into any issues?

Seems that my current setup is successfully doing this. Each of the 4 packages is separate on Bintray.


>The only piece that I think might be missing is that we need to recognize in the Makefile#publish or CI script whether a version is a SNAPSHOT or a stable/alpha version which was previously handled by the maven-release plugin.

Still need to figure this out.

> So, whenever we release a module, during the POM generation we need to iterate through all of its dependencies and for each local dependency we need to overwrite that module value with a correct artifact name and version of the most recent Maven release of that dependency. We can either store those locally, next to the current SNAPSHOT version name or query them from the Maven repository.


So, below is the `services` POM file. Let's say that the `4.9.0` release is going out. https://github.com/mapbox/mapbox-java/blob/master/gradle.properties#L2 would be adjusted to `4.9.0`, so it'd be `4.9.0` everywhere where it currently says `4.9.0-SNAPSHOT` in the POM file below. Would this work? I'm not sure how this is different from what you're suggesting. Perhaps I'm just not seeing a big problem staring me in the face.
![Screen Shot 2019-05-16 at 4 44 15 PM](https://user-images.githubusercontent.com/4394910/57894045-1dfa8f00-77fa-11e9-9517-57cf76a563af.png)

> those dependencies might not be picked up in POM (or are represented poorly, like unknown or wrong artifact names).

Seems that the plugin correctly picked up the dependencies, right?

**Comment by LukasPaczos** [comment]
Yes, seems like the POM is fine :rocket:

**Comment by langsmith** [comment]
Created a pr for the work discussed above https://github.com/mapbox/mapbox-java/pull/1037
